ALTER TABLE "CONVERSATION_SESSIONS"
    ADD COLUMN IF NOT EXISTS "CONTACT_PREFERENCE" VARCHAR(32);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'CHK_CONVERSATION_SESSIONS_CONTACT_PREFERENCE'
    ) THEN
        ALTER TABLE "CONVERSATION_SESSIONS"
            ADD CONSTRAINT "CHK_CONVERSATION_SESSIONS_CONTACT_PREFERENCE"
                CHECK (
                    "CONTACT_PREFERENCE" IS NULL
                    OR "CONTACT_PREFERENCE" IN ('HUMAN_CONTACT', 'SPECIFIC_TIME')
                );
    END IF;
END
$$;
