ALTER TABLE "CONVERSATION_SESSIONS"
    ADD COLUMN IF NOT EXISTS "WAITING_FOR_FIELD" VARCHAR(32);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'CHK_CONVERSATION_SESSIONS_WAITING_FOR_FIELD'
    ) THEN
        ALTER TABLE "CONVERSATION_SESSIONS"
            ADD CONSTRAINT "CHK_CONVERSATION_SESSIONS_WAITING_FOR_FIELD"
                CHECK (
                    "WAITING_FOR_FIELD" IS NULL
                    OR "WAITING_FOR_FIELD" IN ('TREATMENT', 'FIRST_TIME', 'NAME', 'PREFERRED_TIME')
                );
    END IF;
END
$$;
