ALTER TABLE OUTBOUND_MESSAGES
    ADD COLUMN IF NOT EXISTS NEXT_ATTEMPT_AT TIMESTAMP;

ALTER TABLE OUTBOUND_MESSAGES
    ADD COLUMN IF NOT EXISTS LOCKED_AT TIMESTAMP;

CREATE INDEX IF NOT EXISTS IDX_OUTBOUND_MESSAGES_STATUS_NEXT_ATTEMPT
    ON OUTBOUND_MESSAGES (STATUS, NEXT_ATTEMPT_AT, CREATED_AT);

CREATE TABLE IF NOT EXISTS CONVERSATION_PROCESSING_LOCKS (
    PHONE_NUMBER VARCHAR(32) PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);
