ALTER TABLE OUTBOUND_MESSAGES
    ADD COLUMN IF NOT EXISTS EXTERNAL_MESSAGE_ID VARCHAR(120);

CREATE INDEX IF NOT EXISTS IDX_OUTBOUND_MESSAGES_EXTERNAL_MESSAGE_ID
    ON OUTBOUND_MESSAGES (EXTERNAL_MESSAGE_ID);
